### ISSUE TITLE
How to add ngModel attribute to SpecialInput

### ISSUE THREAD

**Issue by GenaANTG** [Attrash-Islam/infinite-autocomplete#42]
Hello!
I'm using Template Driven Forms in Angular2. And every input field in my form has ngModel attribute.
So, how to add ngModel attribute to SpecialInput?

Thank you!

**Comment by Attrash-Islam** [comment]
Hi,
I've created a wrapper for popular frameworks like: AngularJS 1.x and React.js.

Unfortunately, I don't know the syntax of Angular2+, but I guess it will be so easy to create a wrapper for this Core library.. Look at AngularJS/React wrapper, and see how they use this library. 

If you like to create an Angular2 wrapper I'd be glad to open a repo and assign you as Colleborator ♥️

**Comment by Attrash-Islam** [comment]
All the wrappers are binding the autocomplete to a DOM node, and then call inifinityAutocomplete.setConfig to update configurations

**Comment by GenaANTG** [comment]
Thank you! )
